# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DWFMS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'GoogleMaps'
  pod 'Firebase/Messaging'
  
# Pods for DWFMS

  target 'DWFMSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
